version: '3'

# uncomment this code section for localhost networking
services:
  client:
    image: client
    container_name: client
    restart: always
    build:
      context: .
    ports:
      - "8081:8081"
    # devices:
    #   - /dev/video0
    networks:
      - sdc-network
    volumes:
      - ./uploadPictures:/app/uploadPictures

networks:
  sdc-network:
    external: 
      name: "sdc-network"





# # uncomment this code for ip-based networking
# services:
#   client:
#     image: client
#     container_name: client
#     restart: always
#     build:
#       context: .
#     ports:
#       - "8081:8081"
#     devices:
#       - /dev/video0
#     network_mode: "host"

#   rtsp-stream:
#     image: bluenviron/mediamtx:latest-ffmpeg
#     network_mode: "host"
#     devices:
#       - /dev/video2
#     volumes:
#       - ./mediamtx.yml:/mediamtx.yml
#     restart: no



